### ISSUE TITLE
常用css的技巧

### ISSUE THREAD

**Issue by zlxbuzz** [zlxbuzz/blog#2]
**1.单行文字两端对齐**

```html
<div>
  <span>123</span>
  <span>345</span>
</div>
```
```css
div{
  text-align:justify;
  border: 1px solid red;
  overflow: hidden;
}
span{
  display:inline-block;
}
div::after{
  content: '';
  display:inline-block;
  padding-left:100%;
}
```
![image](https://user-images.githubusercontent.com/13307888/33416320-eea1ce7e-d5d6-11e7-8118-62eb8df0f62a.png)
